//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//--


namespace keroBilgisayar.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class keroBilgisayarEntities : DbContext
    {
        public keroBilgisayarEntities()
            : base("name=keroBilgisayarEntities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<kategori> kategori { get; set; }
        public virtual DbSet<projeler> projeler { get; set; }
        public virtual DbSet<projeSiparis> projeSiparis { get; set; }
        public virtual DbSet<uyeler> uyeler { get; set; }
    }
}