//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace keroBilgisayar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class projeler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public projeler()
        {
            this.projeSiparis = new HashSet<projeSiparis>();
        }
    
        public int projeId { get; set; }
        public string projeAdi { get; set; }
        public int projeKatId { get; set; }
        public decimal projeFiyat { get; set; }
        public string projeAciklama { get; set; }
        public string projeGorsel { get; set; }
    
        public virtual kategori kategori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<projeSiparis> projeSiparis { get; set; }
    }
}
